
- name: Install necessary packages
  apt:
    name:
      - bzip2
      - coreutils
      - curl
      - inetutils-ping
      - jq
      - redis-server
      - rsync
      - smbclient
      - ssh
    state: latest
