
- name: Install apt key
  apt_key:
    url: https://download.owncloud.org/download/repositories/production/Ubuntu_20.10/Release.key
    state: present

- name: Install Repo
  apt_repository:
    repo: "deb http://download.owncloud.org/download/repositories/production/Ubuntu_20.10/ /"
    state: present

- name: Install owncloud
  apt:
    name: owncloud-complete-files
    update_cache: yes
    state: latest
