
- include: 'install-ubuntu-20.04.yml'
  become: yes
  become_user: root
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04'

- include: 'install.yml'
  become: yes
  become_user: root
  when: ansible_distribution == 'Ubuntu'
