
- import_tasks: 'deps.yml'
  become: yes
  become_user: root

# - import_tasks: 'ubuntu-20.04.yml'
#   become: yes
#   become_user: root
#   when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04'
#
# - import_tasks: 'configure.yml'
#   become: yes
#   become_user: root
#
# - import_tasks: 'install.yml'
#   become: yes
#   become_user: root
